---
- name: Task Patch Automation
  hosts: App
  tasks:
    - import_tasks: shared_playbook/stop_service.yml
    - import_tasks: shared_playbook/backup.yml
    - import_tasks: shared_playbook/prepare.yml
    - import_tasks: shared_playbook/patching.yml
    - import_tasks: shared_playbook/restart.yml
    - import_tasks: shared_playbook/start_service.yml
